## # yaml-language-server: $schema=https://raw.githubusercontent.com/ejsdotsh/ejscv/refs/heads/main/ejscv.typ.schema.json
# for local development
# yaml-language-server: $schema=../ejscv.typ.schema.json

contact:
  name: ejsdotsh
  location: Remote or hybrid in SF Bay Area
  email: contactme@ejs.sh
  phone: +1-720-663-1873

  links:
    - name: lorem
      url: https://loremipsum.io/

main_summary:
  summary:
    Lorem ipsum dolor sit amet consectetur adipiscing elit. Sit amet consectetur adipiscing elit quisque faucibus ex.
    Adipiscing elit quisque faucibus ex sapien vitae pellentesque.
  highlights:
    - Lorem ipsum dolor sit amet consectetur adipiscing elit.

jobs:
  - company: Lorem Ipsum
    asn:
    title: Network Engineer
    start_date: 2023-10-31
    end_date: 2025-10-30
    location: Remote, California
    summary:
    highlights:
      - Lorem ipsum dolor sit amet consectetur adipiscing elit.
      - Adipiscing elit quisque faucibus ex sapien vitae pellentesque.
      - Vitae pellentesque sem placerat in id cursus mi.
      - Cursus mi pretium tellus duis convallis tempus leo.
      - Tempus leo eu aenean sed diam urna tempor.
      - Urna tempor pulvinar vivamus fringilla lacus nec metus.
    technologies:
      - Dolor
      - Sit
      - Amet
      - Consectetur
      - Adipiscing
      - Elit
      - Quisque
      - Faucibus
      - Ex
      - Sapien

education:
  - institution: Lorem Ipsum College
    area: Ipsum Lorem
    degree: Associate of Arts
    start_date:
    end_date: 2004-05-05
    location: Miami, Florida

certifications:
  - name: Lorem Ipsum Certified Specialist
    start_date: 2012
    end_date: 2015
    current: false
  - name: Lorem Ipsum Certified Expert
    start_date: 2006
    end_date: 2009
    current: true

core_skills:
  # - Network Architecture
  - Network Design
  # - Technical Leadership
  - Consensus Building
  # - Network Engineering
  - IP Peering & Interconnection
  - Security
  - Change Management
  - Managing Change
  - Unix/Linux Systems
  - Capacity Planning
  # - Capacity Management
  - IPv4/IPv6 Address Management
  - Automation and Tooling
  - New Product Implementation
  - System Design
  # - CI/CD
  # - NetDevSecOps
  # - Consultative Selling
  # - GitOps
  - Interviewing
  - Standards Development
  - Technical Documentation

skills:
  - label: Lorem Ipsum
    skill:
      - Dolor
      - Sit
      - Amet
      - Consectetur
      - Adipiscing
      - Elit
      - Quisque
      - Faucibus
      - Ex
      - Sapien

projects:
  - name: EJ's CV (template)
    url: https://github.com/ejsdotsh/ejscv
    start_date: 2025-10
    end_date: present
    summary: Rewriting my LaTeX CV as a Typst template that uses schema-validated YAML for data.
    highlights:

affiliations:
  - name: Lorem Ipsum Group
    url:
    roles:
      - name: Panelist/Speaker, "Operational Experiences with Lorem Ipsum"
        start_date:
        end_date: Feb 2010
      - name: Member
        start_date: 2002-01-01
        end_date: present
    summary:
    highlights:
      - Panel discussion and Q&A discussing operational experiences with Lorem Ipsum
